import { DataContextProvider } from "@/context/data.context";

// export const metadata = {
//   title: "Next App",
//   description: "Generated by create next app",
// };

export default function ServicesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <DataContextProvider>{children}</DataContextProvider>;
}
